### PR TITLE
Remove unstable features

### PR DESCRIPTION
**Pull request by t-mw**
Thanks for these bindings.

I thought it'd be nice to be able to build them with stable rust, and it seems like the unstable features aren't critical.

You might want to reapply `rustfmt` if you merge this, I'm not sure if my settings match yours,.

### CODE REVIEW

**Comment by t-mw** [comment]
Ah sorry, I just saw your comment, I'll try that.

**Comment by t-mw** [comment]
`try!` is being deprecated, but `ok_or` should be easy to switch out once `NoneError` becomes stable.

**Review by 19h — APPROVED** [review]
Thanks for your contribution!

**Comment by 19h** [comment]
I released it as [1.0.1](https://crates.io/crates/ul/1.0.1).

**Pull request merged**
